//Global variable pointing to the current user's Firestore document
var currentUser;

//Function that calls everything needed for the main page
function doAll() {
  firebase.auth().onAuthStateChanged((user) => {
    if (user) {
      currentUser = db.collection("users").doc(user.uid); //global
      getBookmarks(user);
    } else {
      // No user is signed in.
      window.location.href = "login.html";
    }
  });
}
doAll();

function loadUserReportsList(user) {
  let hazardCardTemplate = document.getElementById("hazardCardTemplate");
  let hazardCardGroup = document.getElementById("hazardCardGroup");
      db.collection("users")
        .doc(user.uid)
        .get()
        .then((user) => {
          var reports = user.data().reports;
          reports.forEach((repID) => {
            db.collection("hazards").doc(repID).get().then((doc) => {
      
              console.log(repID.date().title);

              }).catch(error =>{
                console.log(repID);
                db.collection("users").doc(user.uid).update({
                  reports: firebase.firestore.FieldValue.arrayRemove(repID),
                })
              });
          });
        });

}

function getBookmarks(user) {
  db.collection("users").doc(user.uid).get()
      .then(userDoc => {

          // Get the Array of bookmarks
          var bookmarks = userDoc.data().bookmarks;
          
          // Get pointer the new card template
          let newcardTemplate = document.getElementById("hazardCardTemplate");
          let bookmarkedHazardsGroup = document.getElementById("saved_reports");

          // Iterate through the ARRAY of bookmarked hikes (document ID's)
          bookmarks.forEach(hazardID => {
              console.log(hazardID);
              db.collection("hazards").doc(hazardID).get().then(doc => {
                  var title = doc.data().name; // get value of the "name" key
                  var hazardImg = doc.data().code; //get unique ID to each hike to be used for fetching right image
                  var docID = doc.id;  //this is the autogenerated ID of the document
                  
                  //clone the new card
                  let hazardCard = hazardCardTemplate.content.cloneNode(true);

                  //update title and some pertinant information
                  var title = doc.data().title; 
                  var description = doc.data().description; 
                  var timestamp = doc.data().timestamp.toDate();
                  var hazardID = doc.id;
                  let hazardimg = doc.data().image;
                  hazardCard.querySelector('.title').innerHTML = title;     
                  hazardCard.querySelector('.timestamp').innerHTML = new Date(timestamp).toLocaleString();    
                  hazardCard.querySelector('.description').innerHTML = `Description: ${description}`;
                  hazardCard.querySelector('#more').href = "hazard-page.html?hazard=" + hazardID;
                  hazardCard.getElementById('card-image card-img-top').src = hazardimg;

                  //NEW LINE: update to display length, duration, last updated
         

                  //Finally, attach this new card to the gallery
                  bookmarkedHazardsGroup.appendChild(hazardCard);
              })
          });
      })
}

function populateHazards() {
  let hazardCardTemplate = document.getElementById("hazardCardTemplate");
  let hazardCardGroup = document.getElementById("hazardCardGroup");
  
  db.collection("hazards")
  .orderBy('timestamp', "desc")
  .limit(10)
  .get()
      .then(allHazards => {
          hazards = allHazards.docs;
          hazards.forEach(doc => {
              var title = doc.data().title; 
              var description = doc.data().description; 
              var lat = doc.data().lat;
              var lng = doc.data().lng;
              var timestamp = doc.data().timestamp.toDate();
              var hazardID = doc.id;
              let hazardCard = hazardCardTemplate.content.cloneNode(true);
              let hazardimg = doc.data().image;
              hazardCard.querySelector('.title').innerHTML = title;     
              hazardCard.querySelector('.timestamp').innerHTML = new Date(timestamp).toLocaleString();    
              hazardCard.querySelector('.description').innerHTML = `Description: ${description}`;
              hazardCard.querySelector('.lat').innerHTML = `Latitude: ${lat}`;
              hazardCard.querySelector('.lng').innerHTML = `Longitude: ${lng}`;
              hazardCard.querySelector('#more').href = "hazard-page.html?hazard=" + hazardID;
              hazardCard.getElementById('card-image card-img-top').src = hazardimg;
             
              hazardCard.querySelector('i').id = 'save-' + hazardID;          
              hazardCard.querySelector('i').onclick = () => updateBookmark(hazardID);

              currentUser.get().then(userDoc => {
                  //get the user name
                  var bookmarks = userDoc.data().bookmarks;
                  if (bookmarks.includes(hazardID)) {
                     document.getElementById('save-' + hazardID).innerText = 'bookmark';
                  }
            })
          
              hazardCardGroup.appendChild(hazardCard);
          })
      })
}